text_extensions: [ 'css', 'erb', 'haml', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'php', 'rb', 'sass', 'scss', 'txt', 'xhtml', 'xml' ]
output_dir: output
index_filenames: [ 'index.html' ]
enable_output_diff: true
asset_dir: assets
data_sources:
  -
    type: filesystem_unified

    items_root: /

    layouts_root: /
