# ----------------------------------------------------------------------
# config file for Nanoc
# ----------------------------------------------------------------------
text_extensions: [ 'css', 'erb', 'haml', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'php', 'rb', 'sass', 'scss', 'txt', 'xhtml', 'xml' ]
output_dir: output
index_filenames: [ 'index.html' ]
assets_dir: assets
enable_output_diff: false
data_sources:
  -
    type: filesystem_unified

    items_root: /
    
    layouts_root: /
